from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Dict, Any, List
import math

import numpy as np
import pandas as pd


REQUIRED_COLUMNS = ("open", "high", "low", "close", "volume")

@dataclass
class BacktestConfig:
    initial_cash: float = 100_000.0
    commission_per_order: float = 1.00
    slippage_bps: float = 2.0
    bars_per_year: int = 252
    allow_fractional: bool = False


@dataclass
class Order:
    submitted_at: pd.Timestamp
    quantity: int | float
    reason: str = ""


@dataclass
class Fill:
    timestamp: pd.Timestamp
    side: str
    quantity: int | float
    price: float
    notional: float
    commission: float
    slippage_per_share: float
    slippage_total: float
    reason: str = ""


@dataclass
class StrategyState:
    current_position: int | float
    bars_held: int
    cash: float
    equity: float
    avg_price: float


@dataclass
class BacktestResult:
    bars: pd.DataFrame
    signals: pd.DataFrame
    equity_curve: pd.DataFrame
    fills: pd.DataFrame
    trades: pd.DataFrame
    metrics: Dict[str, float]

class Strategy:
    def prepare(self, bars: pd.DataFrame) -> pd.DataFrame:
        return bars.copy()

    def target_position(self, row: pd.Series, state: StrategyState) -> int | float:
        raise NotImplementedError("Strategy subclasses must implement target_position().")


class MeanReversionStrategy(Strategy):
    """
    Z-score mean reversion.

    Rules:
      - z = (close - rolling_mean) / rolling_std
      - long when z <= -entry_z
      - short when z >= +entry_z
      - exit to flat when abs(z) <= exit_z
      - optional max_hold_bars to force an exit
    """

    def __init__(
        self,
        lookback: int = 20,
        entry_z: float = 1.5,
        exit_z: float = 0.5,
        trade_size: int = 100,
        allow_short: bool = True,
        max_hold_bars: Optional[int] = None,
        min_std: float = 1e-12,
    ) -> None:
        if lookback < 2:
            raise ValueError("lookback must be >= 2")
        if exit_z >= entry_z:
            raise ValueError("exit_z should be smaller than entry_z")
        if trade_size <= 0:
            raise ValueError("trade_size must be > 0")
        self.lookback = lookback
        self.entry_z = entry_z
        self.exit_z = exit_z
        self.trade_size = int(trade_size)
        self.allow_short = allow_short
        self.max_hold_bars = max_hold_bars
        self.min_std = min_std

    def prepare(self, bars: pd.DataFrame) -> pd.DataFrame:
        df = bars.copy()
        df["mean"] = df["close"].rolling(self.lookback, min_periods=self.lookback).mean()
        df["std"] = df["close"].rolling(self.lookback, min_periods=self.lookback).std(ddof=0)
        df["std"] = df["std"].where(df["std"] > self.min_std, np.nan)
        df["zscore"] = (df["close"] - df["mean"]) / df["std"]
        return df

    def target_position(self, row: pd.Series, state: StrategyState) -> int:
        z = row.get("zscore", np.nan)
        if pd.isna(z):
            return int(state.current_position)

        # Fail-safe time stop.
        if self.max_hold_bars is not None and state.current_position != 0 and state.bars_held >= self.max_hold_bars:
            return 0

        pos = int(state.current_position)

        if pos == 0:
            if z <= -self.entry_z:
                return self.trade_size
            if self.allow_short and z >= self.entry_z:
                return -self.trade_size
            return 0

        if pos > 0:
            if abs(z) <= self.exit_z or z >= self.entry_z:
                return 0
            return pos

        # pos < 0
        if abs(z) <= self.exit_z or z <= -self.entry_z:
            return 0
        return pos

class Portfolio:
    def __init__(self, initial_cash: float) -> None:
        self.cash = float(initial_cash)
        self.position = 0
        self.avg_price = 0.0
        self.realized_pnl = 0.0

    def equity(self, mark_price: float) -> float:
        return self.cash + self.position * float(mark_price)

    def unrealized_pnl(self, mark_price: float) -> float:
        if self.position == 0:
            return 0.0
        if self.position > 0:
            return (float(mark_price) - self.avg_price) * self.position
        return (self.avg_price - float(mark_price)) * abs(self.position)

    def apply_fill(self, fill: Fill) -> float:
        """
        Applies a signed fill and returns the realized pnl generated by this fill,
        excluding commissions (commissions are deducted directly from cash).
        """
        signed_qty = fill.quantity if fill.side == "BUY" else -fill.quantity
        signed_qty = int(signed_qty) if float(signed_qty).is_integer() else float(signed_qty)

        # Buying spends cash; selling receives cash.
        self.cash -= fill.price * signed_qty
        self.cash -= fill.commission

        if self.position == 0:
            self.position = signed_qty
            self.avg_price = fill.price
            return 0.0

        # Add to same-side position -> update weighted average.
        if np.sign(self.position) == np.sign(signed_qty):
            new_position = self.position + signed_qty
            self.avg_price = (
                abs(self.position) * self.avg_price + abs(signed_qty) * fill.price
            ) / abs(new_position)
            self.position = new_position
            return 0.0

        # Opposite-side fill -> partial close, full close, or reversal.
        closing_qty = min(abs(self.position), abs(signed_qty))
        if self.position > 0:
            realized = (fill.price - self.avg_price) * closing_qty
        else:
            realized = (self.avg_price - fill.price) * closing_qty

        self.realized_pnl += realized
        new_position = self.position + signed_qty

        if new_position == 0:
            self.position = 0
            self.avg_price = 0.0
            return realized

        if np.sign(new_position) == np.sign(self.position):
            # Partial reduction. Avg price stays the same.
            self.position = new_position
            return realized

        # Reversal. Leftover quantity becomes a new position at the fill price.
        self.position = new_position
        self.avg_price = fill.price
        return realized


# =========================
# Validation + Metrics
# =========================

def validate_ohlcv(bars: pd.DataFrame) -> pd.DataFrame:
    if not isinstance(bars, pd.DataFrame):
        raise TypeError("bars must be a pandas DataFrame")

    missing = [c for c in REQUIRED_COLUMNS if c not in bars.columns]
    if missing:
        raise ValueError(f"bars is missing required columns: {missing}")

    df = bars.copy()

    if not isinstance(df.index, pd.DatetimeIndex):
        raise TypeError("bars index must be a pandas DatetimeIndex")

    df = df.sort_index()

    if df.index.has_duplicates:
        raise ValueError("bars index contains duplicate timestamps")

    if df[list(REQUIRED_COLUMNS)].isna().any().any():
        raise ValueError("bars contains NaNs in required OHLCV columns")

    if (df["high"] < df[["open", "close", "low"]].max(axis=1)).any():
        raise ValueError("found rows where high is below open/close/low")
    if (df["low"] > df[["open", "close", "high"]].min(axis=1)).any():
        raise ValueError("found rows where low is above open/close/high")
    if (df["volume"] < 0).any():
        raise ValueError("volume must be non-negative")

    return df


def compute_metrics(
    equity_curve: pd.DataFrame,
    trades: pd.DataFrame,
    fills: pd.DataFrame,
    bars_per_year: int,
) -> Dict[str, float]:
    out: Dict[str, float] = {}
    if equity_curve.empty:
        return out

    eq = equity_curve["equity"].astype(float)
    returns = eq.pct_change().replace([np.inf, -np.inf], np.nan).dropna()

    out["total_return"] = float(eq.iloc[-1] / eq.iloc[0] - 1.0)

    n_periods = len(returns)
    if n_periods > 0 and eq.iloc[0] > 0 and eq.iloc[-1] > 0:
        years = n_periods / bars_per_year
        out["annualized_return"] = float((eq.iloc[-1] / eq.iloc[0]) ** (1 / years) - 1.0) if years > 0 else float("nan")
    else:
        out["annualized_return"] = float("nan")

    if n_periods > 1:
        ret_std = returns.std(ddof=0)
        ann_vol = ret_std * math.sqrt(bars_per_year)
        out["annualized_volatility"] = float(ann_vol)
        out["sharpe_ratio"] = float(returns.mean() / ret_std * math.sqrt(bars_per_year)) if ret_std > 0 else float("nan")

        downside = returns[returns < 0]
        downside_std = downside.std(ddof=0) if len(downside) > 0 else 0.0
        out["sortino_ratio"] = float(returns.mean() / downside_std * math.sqrt(bars_per_year)) if downside_std > 0 else float("nan")
    else:
        out["annualized_volatility"] = float("nan")
        out["sharpe_ratio"] = float("nan")
        out["sortino_ratio"] = float("nan")

    running_max = eq.cummax()
    drawdown = eq / running_max - 1.0
    out["max_drawdown"] = float(drawdown.min())

    if out["max_drawdown"] < 0 and np.isfinite(out["annualized_return"]):
        out["calmar_ratio"] = float(out["annualized_return"] / abs(out["max_drawdown"]))
    else:
        out["calmar_ratio"] = float("nan")

    out["exposure"] = float((equity_curve["position"] != 0).mean())

    if not fills.empty and eq.mean() > 0:
        out["turnover"] = float(fills["notional"].sum() / eq.mean())
    else:
        out["turnover"] = 0.0

    out["num_fills"] = int(len(fills))
    out["num_trades"] = int(len(trades))

    if not trades.empty:
        wins = trades["net_pnl"] > 0
        losses = trades["net_pnl"] < 0

        out["win_rate"] = float(wins.mean())
        out["avg_trade_pnl"] = float(trades["net_pnl"].mean())
        out["median_trade_pnl"] = float(trades["net_pnl"].median())
        out["avg_holding_bars"] = float(trades["holding_bars"].mean())

        gross_profit = trades.loc[wins, "net_pnl"].sum()
        gross_loss = -trades.loc[losses, "net_pnl"].sum()
        out["profit_factor"] = float(gross_profit / gross_loss) if gross_loss > 0 else float("inf")

        avg_win = trades.loc[wins, "net_pnl"].mean() if wins.any() else 0.0
        avg_loss = trades.loc[losses, "net_pnl"].mean() if losses.any() else 0.0
        out["avg_win"] = float(avg_win)
        out["avg_loss"] = float(avg_loss)
        out["expectancy"] = float(out["win_rate"] * avg_win + (1.0 - out["win_rate"]) * avg_loss)
    else:
        out["win_rate"] = float("nan")
        out["avg_trade_pnl"] = float("nan")
        out["median_trade_pnl"] = float("nan")
        out["avg_holding_bars"] = float("nan")
        out["profit_factor"] = float("nan")
        out["avg_win"] = float("nan")
        out["avg_loss"] = float("nan")
        out["expectancy"] = float("nan")

    return out

class BarBacktester:
    """
    Single-asset, bar-based backtester.

    Assumptions:
      - the strategy sees bar t after close[t]
      - orders generated on bar t are filled at open[t+1]
      - market orders only
      - one pending order at a time
    """

    def __init__(self, bars: pd.DataFrame, strategy: Strategy, config: Optional[BacktestConfig] = None) -> None:
        self.bars = validate_ohlcv(bars)
        self.strategy = strategy
        self.config = config or BacktestConfig()

    def _fill_details(self, open_price: float, quantity: int | float) -> tuple[float, float, float]:
        slip_per_share = float(open_price) * (self.config.slippage_bps / 10_000.0)
        fill_price = float(open_price + slip_per_share) if quantity > 0 else float(open_price - slip_per_share)
        slip_total = abs(quantity) * slip_per_share
        return fill_price, slip_per_share, slip_total

    def run(self) -> BacktestResult:
        df = self.strategy.prepare(self.bars)
        df = validate_ohlcv(df)

        portfolio = Portfolio(initial_cash=self.config.initial_cash)

        pending_order: Optional[Order] = None
        signals: List[Dict[str, Any]] = []
        fills: List[Dict[str, Any]] = []
        equity_rows: List[Dict[str, Any]] = []
        trades: List[Dict[str, Any]] = []

        current_trade: Optional[Dict[str, Any]] = None
        bars_held = 0

        for i, (ts, row) in enumerate(df.iterrows()):
            prev_position = portfolio.position

            # 1) Fill any order generated at the prior close.
            if pending_order is not None:
                fill_qty = pending_order.quantity
                fill_price, slip_ps, slip_total = self._fill_details(row["open"], fill_qty)

                fill = Fill(
                    timestamp=ts,
                    side="BUY" if fill_qty > 0 else "SELL",
                    quantity=abs(fill_qty),
                    price=fill_price,
                    notional=abs(fill_qty) * fill_price,
                    commission=self.config.commission_per_order,
                    slippage_per_share=slip_ps,
                    slippage_total=slip_total,
                    reason=pending_order.reason,
                )
                realized_from_fill = portfolio.apply_fill(fill)

                fills.append(
                    {
                        "timestamp": fill.timestamp,
                        "side": fill.side,
                        "quantity": fill.quantity,
                        "price": fill.price,
                        "notional": fill.notional,
                        "commission": fill.commission,
                        "slippage_per_share": fill.slippage_per_share,
                        "slippage_total": fill.slippage_total,
                        "reason": fill.reason,
                        "realized_pnl_from_fill": realized_from_fill,
                        "position_after_fill": portfolio.position,
                        "cash_after_fill": portfolio.cash,
                    }
                )

                new_position = portfolio.position
                fee = fill.commission

                # Trade bookkeeping. This is exact for flat->position->flat
                # and also handles reversals by splitting the fee proportionally.
                if prev_position == 0 and new_position != 0:
                    current_trade = {
                        "entry_time": ts,
                        "direction": "LONG" if new_position > 0 else "SHORT",
                        "quantity": abs(new_position),
                        "entry_price": fill.price,
                        "entry_reason": fill.reason,
                        "fees": fee,
                    }
                    bars_held = 0

                elif prev_position != 0 and new_position == 0:
                    if current_trade is not None:
                        qty = current_trade["quantity"]
                        exit_price = fill.price
                        gross = (exit_price - current_trade["entry_price"]) * qty if current_trade["direction"] == "LONG" \
                            else (current_trade["entry_price"] - exit_price) * qty
                        total_fees = current_trade["fees"] + fee
                        trades.append(
                            {
                                "entry_time": current_trade["entry_time"],
                                "exit_time": ts,
                                "direction": current_trade["direction"],
                                "quantity": qty,
                                "entry_price": current_trade["entry_price"],
                                "exit_price": exit_price,
                                "gross_pnl": gross,
                                "fees": total_fees,
                                "net_pnl": gross - total_fees,
                                "holding_bars": bars_held,
                                "entry_reason": current_trade["entry_reason"],
                                "exit_reason": fill.reason,
                            }
                        )
                    current_trade = None
                    bars_held = 0

                elif prev_position != 0 and np.sign(prev_position) != np.sign(new_position):
                    close_qty = abs(prev_position)
                    open_qty = abs(new_position)
                    total_qty = close_qty + open_qty
                    close_fee = fee * close_qty / total_qty
                    open_fee = fee * open_qty / total_qty

                    if current_trade is not None:
                        qty = current_trade["quantity"]
                        exit_price = fill.price
                        gross = (exit_price - current_trade["entry_price"]) * qty if current_trade["direction"] == "LONG" \
                            else (current_trade["entry_price"] - exit_price) * qty
                        total_fees = current_trade["fees"] + close_fee
                        trades.append(
                            {
                                "entry_time": current_trade["entry_time"],
                                "exit_time": ts,
                                "direction": current_trade["direction"],
                                "quantity": qty,
                                "entry_price": current_trade["entry_price"],
                                "exit_price": exit_price,
                                "gross_pnl": gross,
                                "fees": total_fees,
                                "net_pnl": gross - total_fees,
                                "holding_bars": bars_held,
                                "entry_reason": current_trade["entry_reason"],
                                "exit_reason": fill.reason,
                            }
                        )

                    current_trade = {
                        "entry_time": ts,
                        "direction": "LONG" if new_position > 0 else "SHORT",
                        "quantity": abs(new_position),
                        "entry_price": fill.price,
                        "entry_reason": fill.reason,
                        "fees": open_fee,
                    }
                    bars_held = 0

                else:
                    # Same-side scaling or partial reduction.
                    if current_trade is not None:
                        current_trade["quantity"] = abs(portfolio.position)
                        current_trade["entry_price"] = portfolio.avg_price
                        current_trade["fees"] += fee

                pending_order = None

            # 2) Update bars held after the fill.
            if portfolio.position != 0:
                bars_held += 1
            else:
                bars_held = 0

            # 3) Mark to market on the close.
            eq = portfolio.equity(row["close"])
            equity_rows.append(
                {
                    "timestamp": ts,
                    "open": row["open"],
                    "high": row["high"],
                    "low": row["low"],
                    "close": row["close"],
                    "volume": row["volume"],
                    "position": portfolio.position,
                    "avg_price": portfolio.avg_price,
                    "cash": portfolio.cash,
                    "realized_pnl": portfolio.realized_pnl,
                    "unrealized_pnl": portfolio.unrealized_pnl(row["close"]),
                    "equity": eq,
                }
            )

            # 4) Generate target position for next bar.
            if i < len(df) - 1:
                state = StrategyState(
                    current_position=portfolio.position,
                    bars_held=bars_held,
                    cash=portfolio.cash,
                    equity=eq,
                    avg_price=portfolio.avg_price,
                )
                target = self.strategy.target_position(row, state)

                if not self.config.allow_fractional and not float(target).is_integer():
                    raise ValueError("strategy returned fractional target_position while allow_fractional=False")

                delta = target - portfolio.position
                delta = int(delta) if float(delta).is_integer() else float(delta)

                signals.append(
                    {
                        "timestamp": ts,
                        "close": row["close"],
                        "target_position": target,
                        "current_position": portfolio.position,
                        "order_quantity_next_bar": delta,
                        "zscore": row.get("zscore", np.nan),
                    }
                )

                if delta != 0:
                    if target == 0:
                        reason = "exit"
                    elif portfolio.position == 0 and target > 0:
                        reason = "enter_long"
                    elif portfolio.position == 0 and target < 0:
                        reason = "enter_short"
                    elif np.sign(target) != np.sign(portfolio.position):
                        reason = "reverse"
                    else:
                        reason = "rebalance"
                    pending_order = Order(submitted_at=ts, quantity=delta, reason=reason)

        equity_df = pd.DataFrame(equity_rows).set_index("timestamp")

        if signals:
            signals_df = pd.DataFrame(signals).set_index("timestamp")
        else:
            signals_df = pd.DataFrame(
                columns=["close", "target_position", "current_position", "order_quantity_next_bar", "zscore"]
            )

        fills_df = pd.DataFrame(fills)
        if not fills_df.empty:
            fills_df = fills_df.set_index("timestamp")
        else:
            fills_df = pd.DataFrame(
                columns=[
                    "side",
                    "quantity",
                    "price",
                    "notional",
                    "commission",
                    "slippage_per_share",
                    "slippage_total",
                    "reason",
                    "realized_pnl_from_fill",
                    "position_after_fill",
                    "cash_after_fill",
                ]
            )

        trades_df = pd.DataFrame(trades)
        if not trades_df.empty:
            trades_df["entry_time"] = pd.to_datetime(trades_df["entry_time"])
            trades_df["exit_time"] = pd.to_datetime(trades_df["exit_time"])

        metrics = compute_metrics(
            equity_curve=equity_df,
            trades=trades_df,
            fills=fills_df.reset_index() if not fills_df.empty else fills_df,
            bars_per_year=self.config.bars_per_year,
        )

        return BacktestResult(
            bars=df,
            signals=signals_df,
            equity_curve=equity_df,
            fills=fills_df,
            trades=trades_df,
            metrics=metrics,
        )


# =========================
# Synthetic data
# =========================

def make_oscillating_ohlcv(n: int = 500, freq: str = "D", seed: int = 7) -> pd.DataFrame:
    """
    Oscillating price path that mean reversion should usually handle better.
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2020-01-01", periods=n, freq=freq)
    base = 100.0 + 5.0 * np.sin(np.linspace(0, 40 * np.pi, n))  # ~20 cycles
    close = base + rng.normal(0.0, 0.3, size=n)
    open_ = np.roll(close, 1)
    open_[0] = close[0]
    high = np.maximum(open_, close) + rng.uniform(0.1, 0.7, size=n)
    low = np.minimum(open_, close) - rng.uniform(0.1, 0.7, size=n)
    volume = rng.integers(5_000, 15_000, size=n)
    return pd.DataFrame({"open": open_, "high": high, "low": low, "close": close, "volume": volume}, index=idx)


def make_trending_ohlcv(n: int = 500, freq: str = "D", seed: int = 7) -> pd.DataFrame:
    """
    Strong trend path that mean reversion should usually struggle against.
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2020-01-01", periods=n, freq=freq)
    close = 100.0 + np.linspace(0.0, 80.0, n) + rng.normal(0.0, 0.1, size=n)
    open_ = np.roll(close, 1)
    open_[0] = close[0]
    high = np.maximum(open_, close) + rng.uniform(0.1, 0.7, size=n)
    low = np.minimum(open_, close) - rng.uniform(0.1, 0.7, size=n)
    volume = rng.integers(5_000, 15_000, size=n)
    return pd.DataFrame({"open": open_, "high": high, "low": low, "close": close, "volume": volume}, index=idx)


def make_random_walk_ohlcv(n: int = 500, freq: str = "D", seed: int = 7) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2020-01-01", periods=n, freq=freq)
    returns = rng.normal(0.0, 0.01, size=n)
    close = 100.0 * np.cumprod(1.0 + returns)
    open_ = np.roll(close, 1)
    open_[0] = close[0]
    high = np.maximum(open_, close) + rng.uniform(0.1, 0.7, size=n)
    low = np.minimum(open_, close) - rng.uniform(0.1, 0.7, size=n)
    volume = rng.integers(5_000, 15_000, size=n)
    return pd.DataFrame({"open": open_, "high": high, "low": low, "close": close, "volume": volume}, index=idx)


def run_validation_suite() -> Dict[str, Dict[str, float]]:
    datasets = {
        "oscillating": make_oscillating_ohlcv(),
        "trending": make_trending_ohlcv(),
        "random_walk": make_random_walk_ohlcv(),
    }

    strategy = MeanReversionStrategy(
        lookback=20,
        entry_z=1.5,
        exit_z=0.5,
        trade_size=100,
        allow_short=True,
        max_hold_bars=15,
    )

    config = BacktestConfig(
        initial_cash=100_000.0,
        commission_per_order=1.0,
        slippage_bps=2.0,
        bars_per_year=252,
    )

    results: Dict[str, Dict[str, float]] = {}
    for name, bars in datasets.items():
        bt = BarBacktester(bars=bars, strategy=strategy, config=config)
        results[name] = bt.run().metrics
    return results


# =========================
# Example usage
# =========================

if __name__ == "__main__":
    bars = make_oscillating_ohlcv(n=400)

    strategy = MeanReversionStrategy(
        lookback=20,
        entry_z=1.5,
        exit_z=0.5,
        trade_size=100,
        allow_short=True,
        max_hold_bars=15,
    )

    config = BacktestConfig(
        initial_cash=100_000.0,
        commission_per_order=1.0,
        slippage_bps=2.0,
        bars_per_year=252,
    )

    bt = BarBacktester(bars=bars, strategy=strategy, config=config)
    result = bt.run()

    print("=== Metrics ===")
    for k, v in result.metrics.items():
        print(f"{k:>24}: {v}")

    print("\n=== Last 5 equity rows ===")
    print(result.equity_curve.tail())

    print("\n=== Validation suite ===")
    validation = run_validation_suite()
    for dataset_name, metrics in validation.items():
        print(f"\n{dataset_name}")
        for k, v in metrics.items():
            print(f"{k:>24}: {v}")
